export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_EVENT: "DUPLICATE_EVENT",
  SOURCE_INACTIVE: "SOURCE_INACTIVE",
  LOT_INACTIVE: "LOT_INACTIVE",
  RULE_CONFLICT: "RULE_CONFLICT",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  VIOLATION_STATE_INVALID: "VIOLATION_STATE_INVALID",
  TEST_MODE_ONLY: "TEST_MODE_ONLY",
  PROCESSING_LOCK_EXISTS: "PROCESSING_LOCK_EXISTS",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
